[build]
  command = "npm run build"
  publish = ".next"  # For SSR/API routes

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[functions]
  directory = ".next/server/app/api"  # Correct for App Router
  node_bundler = "esbuild"  # Faster builds
  runtime = "nodejs18.x"    # Recommended runtime

[dev]
  framework = "next"  # Better local dev experience
  autoLaunch = true   # Automatically open browser
